#include <ezira/protocol/get_config.hpp>
#include <ezira/protocol/config.hpp>
#include <ezira/protocol/asset.hpp>
#include <ezira/protocol/types.hpp>
#include <ezira/protocol/version.hpp>

namespace ezira { namespace protocol {

fc::variant_object get_config()
{
   fc::mutable_variant_object result;

#ifdef IS_TEST_NET
   result[ "IS_TEST_NET" ] = true;
#else
   result[ "IS_TEST_NET" ] = false;
#endif

   result["EZD_SYMBOL"] = EZD_SYMBOL;
   result["EZIRA_100_PERCENT"] = EZIRA_100_PERCENT;
   result["EZIRA_1_PERCENT"] = EZIRA_1_PERCENT;
   result["EZIRA_1_TENTH_PERCENT"] = EZIRA_1_TENTH_PERCENT;
   result["EZIRA_ACCOUNT_RECOVERY_REQUEST_EXPIRATION_PERIOD"] = EZIRA_ACCOUNT_RECOVERY_REQUEST_EXPIRATION_PERIOD;
   result["EZIRA_ACTIVE_CHALLENGE_COOLDOWN"] = EZIRA_ACTIVE_CHALLENGE_COOLDOWN;
   result["EZIRA_ACTIVE_CHALLENGE_FEE"] = EZIRA_ACTIVE_CHALLENGE_FEE;
   result["EZIRA_ADDRESS_PREFIX"] = EZIRA_ADDRESS_PREFIX;
   result["EZIRA_APR_PERCENT_MULTIPLY_PER_BLOCK"] = EZIRA_APR_PERCENT_MULTIPLY_PER_BLOCK;
   result["EZIRA_APR_PERCENT_MULTIPLY_PER_HOUR"] = EZIRA_APR_PERCENT_MULTIPLY_PER_HOUR;
   result["EZIRA_APR_PERCENT_MULTIPLY_PER_ROUND"] = EZIRA_APR_PERCENT_MULTIPLY_PER_ROUND;
   result["EZIRA_APR_PERCENT_SHIFT_PER_BLOCK"] = EZIRA_APR_PERCENT_SHIFT_PER_BLOCK;
   result["EZIRA_APR_PERCENT_SHIFT_PER_HOUR"] = EZIRA_APR_PERCENT_SHIFT_PER_HOUR;
   result["EZIRA_APR_PERCENT_SHIFT_PER_ROUND"] = EZIRA_APR_PERCENT_SHIFT_PER_ROUND;
   result["EZIRA_BANDWIDTH_AVERAGE_WINDOW_SECONDS"] = EZIRA_BANDWIDTH_AVERAGE_WINDOW_SECONDS;
   result["EZIRA_BANDWIDTH_PRECISION"] = EZIRA_BANDWIDTH_PRECISION;
   result["EZIRA_BLOCKCHAIN_PRECISION"] = EZIRA_BLOCKCHAIN_PRECISION;
   result["EZIRA_BLOCKCHAIN_PRECISION_DIGITS"] = EZIRA_BLOCKCHAIN_PRECISION_DIGITS;
   result["EZIRA_BLOCKCHAIN_HARDFORK_VERSION"] = EZIRA_BLOCKCHAIN_HARDFORK_VERSION;
   result["EZIRA_BLOCKCHAIN_VERSION"] = EZIRA_BLOCKCHAIN_VERSION;
   result["EZIRA_BLOCK_INTERVAL"] = EZIRA_BLOCK_INTERVAL;
   result["EZIRA_BLOCKS_PER_DAY"] = EZIRA_BLOCKS_PER_DAY;
   result["EZIRA_BLOCKS_PER_HOUR"] = EZIRA_BLOCKS_PER_HOUR;
   result["EZIRA_BLOCKS_PER_YEAR"] = EZIRA_BLOCKS_PER_YEAR;
   result["EZIRA_CASHOUT_WINDOW_SECONDS"] = EZIRA_CASHOUT_WINDOW_SECONDS;
   result["EZIRA_CASHOUT_WINDOW_SECONDS_PRE_HF12"] = EZIRA_CASHOUT_WINDOW_SECONDS_PRE_HF12;
   result["EZIRA_CASHOUT_WINDOW_SECONDS_PRE_HF17"] = EZIRA_CASHOUT_WINDOW_SECONDS_PRE_HF17;
   result["EZIRA_CHAIN_ID"] = EZIRA_CHAIN_ID;
   result["EZIRA_COMMENT_REWARD_FUND_NAME"] = EZIRA_COMMENT_REWARD_FUND_NAME;
   result["EZIRA_CONTENT_APR_PERCENT"] = EZIRA_CONTENT_APR_PERCENT;
   result["EZIRA_CONTENT_CONSTANT_HF0"] = EZIRA_CONTENT_CONSTANT_HF0;
   result["EZIRA_CONTENT_REWARD_PERCENT"] = EZIRA_CONTENT_REWARD_PERCENT;
   result["EZIRA_CONVERSION_DELAY"] = EZIRA_CONVERSION_DELAY;
   result["EZIRA_CONVERSION_DELAY_PRE_HF_16"] = EZIRA_CONVERSION_DELAY_PRE_HF_16;
   result["EZIRA_CREATE_ACCOUNT_DELEGATION_RATIO"] = EZIRA_CREATE_ACCOUNT_DELEGATION_RATIO;
   result["EZIRA_CREATE_ACCOUNT_DELEGATION_TIME"] = EZIRA_CREATE_ACCOUNT_DELEGATION_TIME;
   result["EZIRA_CREATE_ACCOUNT_WITH_EZIRA_MODIFIER"] = EZIRA_CREATE_ACCOUNT_WITH_EZIRA_MODIFIER;
   result["EZIRA_CURATE_APR_PERCENT"] = EZIRA_CURATE_APR_PERCENT;
   result["EZIRA_DEFAULT_EZD_INTEREST_RATE"] = EZIRA_DEFAULT_EZD_INTEREST_RATE;
   result["EZIRA_EQUIHASH_K"] = EZIRA_EQUIHASH_K;
   result["EZIRA_EQUIHASH_N"] = EZIRA_EQUIHASH_N;
   result["EZIRA_FEED_HISTORY_WINDOW"] = EZIRA_FEED_HISTORY_WINDOW;
   result["EZIRA_FEED_HISTORY_WINDOW_PRE_HF_16"] = EZIRA_FEED_HISTORY_WINDOW_PRE_HF_16;
   result["EZIRA_FEED_INTERVAL_BLOCKS"] = EZIRA_FEED_INTERVAL_BLOCKS;
   result["EZIRA_FREE_TRANSACTIONS_WITH_NEW_ACCOUNT"] = EZIRA_FREE_TRANSACTIONS_WITH_NEW_ACCOUNT;
   result["EZIRA_GENESIS_TIME"] = EZIRA_GENESIS_TIME;
   result["EZIRA_HARDFORK_REQUIRED_WITNESSES"] = EZIRA_HARDFORK_REQUIRED_WITNESSES;
   result["EZIRA_INFLATION_NARROWING_PERIOD"] = EZIRA_INFLATION_NARROWING_PERIOD;
   result["EZIRA_INFLATION_RATE_START_PERCENT"] = EZIRA_INFLATION_RATE_START_PERCENT;
   result["EZIRA_INFLATION_RATE_STOP_PERCENT"] = EZIRA_INFLATION_RATE_STOP_PERCENT;
   result["EZIRA_INIT_MINER_NAME"] = EZIRA_INIT_MINER_NAME;
   result["EZIRA_INIT_PUBLIC_KEY_STR"] = EZIRA_INIT_PUBLIC_KEY_STR;
#if 0
   // do not expose private key, period.
   // we need this line present but inactivated so CI check for all constants in config.hpp doesn't complain.
   result["EZIRA_INIT_PRIVATE_KEY"] = EZIRA_INIT_PRIVATE_KEY;
#endif
   result["EZIRA_INIT_SUPPLY"] = EZIRA_INIT_SUPPLY;
   result["EZIRA_INIT_TIME"] = EZIRA_INIT_TIME;
   result["EZIRA_IRREVERSIBLE_THRESHOLD"] = EZIRA_IRREVERSIBLE_THRESHOLD;
   result["EZIRA_LIQUIDITY_APR_PERCENT"] = EZIRA_LIQUIDITY_APR_PERCENT;
   result["EZIRA_LIQUIDITY_REWARD_BLOCKS"] = EZIRA_LIQUIDITY_REWARD_BLOCKS;
   result["EZIRA_LIQUIDITY_REWARD_PERIOD_SEC"] = EZIRA_LIQUIDITY_REWARD_PERIOD_SEC;
   result["EZIRA_LIQUIDITY_TIMEOUT_SEC"] = EZIRA_LIQUIDITY_TIMEOUT_SEC;
   result["EZIRA_MAX_ACCOUNT_NAME_LENGTH"] = EZIRA_MAX_ACCOUNT_NAME_LENGTH;
   result["EZIRA_MAX_ACCOUNT_WITNESS_VOTES"] = EZIRA_MAX_ACCOUNT_WITNESS_VOTES;
   result["EZIRA_MAX_ASSET_WHITELIST_AUTHORITIES"] = EZIRA_MAX_ASSET_WHITELIST_AUTHORITIES;
   result["EZIRA_MAX_AUTHORITY_MEMBERSHIP"] = EZIRA_MAX_AUTHORITY_MEMBERSHIP;
   result["EZIRA_MAX_BLOCK_SIZE"] = EZIRA_MAX_BLOCK_SIZE;
   result["EZIRA_MAX_CASHOUT_WINDOW_SECONDS"] = EZIRA_MAX_CASHOUT_WINDOW_SECONDS;
   result["EZIRA_MAX_COMMENT_DEPTH"] = EZIRA_MAX_COMMENT_DEPTH;
   result["EZIRA_MAX_COMMENT_DEPTH_PRE_HF17"] = EZIRA_MAX_COMMENT_DEPTH_PRE_HF17;
   result["EZIRA_MAX_FEED_AGE_SECONDS"] = EZIRA_MAX_FEED_AGE_SECONDS;
   result["EZIRA_MAX_INSTANCE_ID"] = EZIRA_MAX_INSTANCE_ID;
   result["EZIRA_MAX_MEMO_SIZE"] = EZIRA_MAX_MEMO_SIZE;
   result["EZIRA_MAX_WITNESSES"] = EZIRA_MAX_WITNESSES;
   result["EZIRA_MAX_MINER_WITNESSES_HF0"] = EZIRA_MAX_MINER_WITNESSES_HF0;
   result["EZIRA_MAX_MINER_WITNESSES_HF17"] = EZIRA_MAX_MINER_WITNESSES_HF17;
   result["EZIRA_MAX_PERMLINK_LENGTH"] = EZIRA_MAX_PERMLINK_LENGTH;
   result["EZIRA_MAX_PROXY_RECURSION_DEPTH"] = EZIRA_MAX_PROXY_RECURSION_DEPTH;
   result["EZIRA_MAX_RATION_DECAY_RATE"] = EZIRA_MAX_RATION_DECAY_RATE;
   result["EZIRA_MAX_RESERVE_RATIO"] = EZIRA_MAX_RESERVE_RATIO;
   result["EZIRA_MAX_RUNNER_WITNESSES_HF0"] = EZIRA_MAX_RUNNER_WITNESSES_HF0;
   result["EZIRA_MAX_RUNNER_WITNESSES_HF17"] = EZIRA_MAX_RUNNER_WITNESSES_HF17;
   result["EZIRA_MAX_SHARE_SUPPLY"] = EZIRA_MAX_SHARE_SUPPLY;
   result["EZIRA_MAX_SIG_CHECK_DEPTH"] = EZIRA_MAX_SIG_CHECK_DEPTH;
   result["EZIRA_MAX_TIME_UNTIL_EXPIRATION"] = EZIRA_MAX_TIME_UNTIL_EXPIRATION;
   result["EZIRA_MAX_TRANSACTION_SIZE"] = EZIRA_MAX_TRANSACTION_SIZE;
   result["EZIRA_MAX_UNDO_HISTORY"] = EZIRA_MAX_UNDO_HISTORY;
   result["EZIRA_MAX_URL_LENGTH"] = EZIRA_MAX_URL_LENGTH;
   result["EZIRA_MAX_VOTE_CHANGES"] = EZIRA_MAX_VOTE_CHANGES;
   result["EZIRA_MAX_VOTED_WITNESSES_HF0"] = EZIRA_MAX_VOTED_WITNESSES_HF0;
   result["EZIRA_MAX_VOTED_WITNESSES_HF17"] = EZIRA_MAX_VOTED_WITNESSES_HF17;
   result["EZIRA_MAX_WITHDRAW_ROUTES"] = EZIRA_MAX_WITHDRAW_ROUTES;
   result["EZIRA_MAX_WITNESS_URL_LENGTH"] = EZIRA_MAX_WITNESS_URL_LENGTH;
   result["EZIRA_MIN_ACCOUNT_CREATION_FEE"] = EZIRA_MIN_ACCOUNT_CREATION_FEE;
   result["EZIRA_MIN_ACCOUNT_NAME_LENGTH"] = EZIRA_MIN_ACCOUNT_NAME_LENGTH;
   result["EZIRA_MIN_BLOCK_SIZE"] = EZIRA_MIN_BLOCK_SIZE;
   result["EZIRA_MIN_BLOCK_SIZE_LIMIT"] = EZIRA_MIN_BLOCK_SIZE_LIMIT;
   result["EZIRA_MIN_CONTENT_REWARD"] = EZIRA_MIN_CONTENT_REWARD;
   result["EZIRA_MIN_CURATE_REWARD"] = EZIRA_MIN_CURATE_REWARD;
   result["EZIRA_MIN_PERMLINK_LENGTH"] = EZIRA_MIN_PERMLINK_LENGTH;
   result["EZIRA_MIN_REPLY_INTERVAL"] = EZIRA_MIN_REPLY_INTERVAL;
   result["EZIRA_MIN_ROOT_COMMENT_INTERVAL"] = EZIRA_MIN_ROOT_COMMENT_INTERVAL;
   result["EZIRA_MIN_VOTE_INTERVAL_SEC"] = EZIRA_MIN_VOTE_INTERVAL_SEC;
   result["EZIRA_MINER_ACCOUNT"] = EZIRA_MINER_ACCOUNT;
   result["EZIRA_MINER_PAY_PERCENT"] = EZIRA_MINER_PAY_PERCENT;
   result["EZIRA_MIN_FEEDS"] = EZIRA_MIN_FEEDS;
   result["EZIRA_MINING_REWARD"] = EZIRA_MINING_REWARD;
   result["EZIRA_MINING_TIME"] = EZIRA_MINING_TIME;
   result["EZIRA_MIN_LIQUIDITY_REWARD"] = EZIRA_MIN_LIQUIDITY_REWARD;
   result["EZIRA_MIN_LIQUIDITY_REWARD_PERIOD_SEC"] = EZIRA_MIN_LIQUIDITY_REWARD_PERIOD_SEC;
   result["EZIRA_MIN_PAYOUT_EZD"] = EZIRA_MIN_PAYOUT_EZD;
   result["EZIRA_MIN_POW_REWARD"] = EZIRA_MIN_POW_REWARD;
   result["EZIRA_MIN_PRODUCER_REWARD"] = EZIRA_MIN_PRODUCER_REWARD;
   result["EZIRA_MIN_RATION"] = EZIRA_MIN_RATION;
   result["EZIRA_MIN_TRANSACTION_EXPIRATION_LIMIT"] = EZIRA_MIN_TRANSACTION_EXPIRATION_LIMIT;
   result["EZIRA_MIN_TRANSACTION_SIZE_LIMIT"] = EZIRA_MIN_TRANSACTION_SIZE_LIMIT;
   result["EZIRA_MIN_UNDO_HISTORY"] = EZIRA_MIN_UNDO_HISTORY;
   result["EZIRA_NULL_ACCOUNT"] = EZIRA_NULL_ACCOUNT;
   result["EZIRA_NUM_INIT_MINERS"] = EZIRA_NUM_INIT_MINERS;
   result["EZIRA_NUM_INIT_EXTRAS"] = EZIRA_NUM_INIT_EXTRAS;
   result["EZIRA_ORIGINAL_MIN_ACCOUNT_CREATION_FEE"] = EZIRA_ORIGINAL_MIN_ACCOUNT_CREATION_FEE;
   result["EZIRA_OWNER_AUTH_HISTORY_TRACKING_START_BLOCK_NUM"] = EZIRA_OWNER_AUTH_HISTORY_TRACKING_START_BLOCK_NUM;
   result["EZIRA_OWNER_AUTH_RECOVERY_PERIOD"] = EZIRA_OWNER_AUTH_RECOVERY_PERIOD;
   result["EZIRA_OWNER_CHALLENGE_COOLDOWN"] = EZIRA_OWNER_CHALLENGE_COOLDOWN;
   result["EZIRA_OWNER_CHALLENGE_FEE"] = EZIRA_OWNER_CHALLENGE_FEE;
   result["EZIRA_OWNER_UPDATE_LIMIT"] = EZIRA_OWNER_UPDATE_LIMIT;
   result["EZIRA_POST_AVERAGE_WINDOW"] = EZIRA_POST_AVERAGE_WINDOW;
   result["EZIRA_POST_MAX_BANDWIDTH"] = EZIRA_POST_MAX_BANDWIDTH;
   result["EZIRA_POST_REWARD_FUND_NAME"] = EZIRA_POST_REWARD_FUND_NAME;
   result["EZIRA_POST_WEIGHT_CONSTANT"] = EZIRA_POST_WEIGHT_CONSTANT;
   result["EZIRA_POW_APR_PERCENT"] = EZIRA_POW_APR_PERCENT;
   result["EZIRA_PRODUCER_APR_PERCENT"] = EZIRA_PRODUCER_APR_PERCENT;
   result["EZIRA_PROXY_TO_SELF_ACCOUNT"] = EZIRA_PROXY_TO_SELF_ACCOUNT;
   result["EZIRA_EZD_INTEREST_COMPOUND_INTERVAL_SEC"] = EZIRA_EZD_INTEREST_COMPOUND_INTERVAL_SEC;
   result["EZIRA_SECONDS_PER_YEAR"] = EZIRA_SECONDS_PER_YEAR;
   result["EZIRA_RECENT_RSHARES_DECAY_RATE_HF19"] = EZIRA_RECENT_RSHARES_DECAY_RATE_HF19;
   result["EZIRA_RECENT_RSHARES_DECAY_RATE_HF17"] = EZIRA_RECENT_RSHARES_DECAY_RATE_HF17;
   result["EZIRA_REVERSE_AUCTION_WINDOW_SECONDS"] = EZIRA_REVERSE_AUCTION_WINDOW_SECONDS;
   result["EZIRA_ROOT_POST_PARENT"] = EZIRA_ROOT_POST_PARENT;
   result["EZIRA_SAVINGS_WITHDRAW_REQUEST_LIMIT"] = EZIRA_SAVINGS_WITHDRAW_REQUEST_LIMIT;
   result["EZIRA_SAVINGS_WITHDRAW_TIME"] = EZIRA_SAVINGS_WITHDRAW_TIME;
   result["EZIRA_EZD_START_PERCENT"] = EZIRA_EZD_START_PERCENT;
   result["EZIRA_EZD_STOP_PERCENT"] = EZIRA_EZD_STOP_PERCENT;
   result["EZIRA_SECOND_CASHOUT_WINDOW"] = EZIRA_SECOND_CASHOUT_WINDOW;
   result["EZIRA_SOFT_MAX_COMMENT_DEPTH"] = EZIRA_SOFT_MAX_COMMENT_DEPTH;
   result["EZIRA_START_MINER_VOTING_BLOCK"] = EZIRA_START_MINER_VOTING_BLOCK;
   result["EZIRA_START_VESTING_BLOCK"] = EZIRA_START_VESTING_BLOCK;
   result["EZIRA_TEMP_ACCOUNT"] = EZIRA_TEMP_ACCOUNT;
   result["EZIRA_UPVOTE_LOCKOUT_HF7"] = EZIRA_UPVOTE_LOCKOUT_HF7;
   result["EZIRA_UPVOTE_LOCKOUT_HF17"] = EZIRA_UPVOTE_LOCKOUT_HF17;
   result["EZIRA_VESTING_FUND_PERCENT"] = EZIRA_VESTING_FUND_PERCENT;
   result["EZIRA_VESTING_WITHDRAW_INTERVALS"] = EZIRA_VESTING_WITHDRAW_INTERVALS;
   result["EZIRA_VESTING_WITHDRAW_INTERVALS_PRE_HF_16"] = EZIRA_VESTING_WITHDRAW_INTERVALS_PRE_HF_16;
   result["EZIRA_VESTING_WITHDRAW_INTERVAL_SECONDS"] = EZIRA_VESTING_WITHDRAW_INTERVAL_SECONDS;
   result["EZIRA_VOTE_CHANGE_LOCKOUT_PERIOD"] = EZIRA_VOTE_CHANGE_LOCKOUT_PERIOD;
   result["EZIRA_VOTE_DUST_THRESHOLD"] = EZIRA_VOTE_DUST_THRESHOLD;
   result["EZIRA_VOTE_REGENERATION_SECONDS"] = EZIRA_VOTE_REGENERATION_SECONDS;
   result["EZIRA_SYMBOL"] = EZIRA_SYMBOL;
   result["VESTS_SYMBOL"] = VESTS_SYMBOL;
   result["VIRTUAL_SCHEDULE_LAP_LENGTH"] = VIRTUAL_SCHEDULE_LAP_LENGTH;
   result["VIRTUAL_SCHEDULE_LAP_LENGTH2"] = VIRTUAL_SCHEDULE_LAP_LENGTH2;

   return result;
}

} } // ezira::protocol
